sudo: false
language: python
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
script:
  - pip3 --version
  - python3 -m pytest tests
before_deploy: pip install twine --user
deploy:
  provider: pypi
  user: sqlcollection
  edge:
    branch: v1.8.45
  password:
    secure: NQBNkMe3IbKjMc5ZH5J3G25XMS+/ZjGmY8aDdjamlWLM5EdcwndPVSBll+0dsIujK0B/IrA4bxiIIZOiaCrLt2faXnp0+0a//noBTdASImmfH2ZmtyZNBbmxEjpQRjCT6FrBAf6/lVIs3SVE1uDNrhv7dG6SFreRgQf0RxNzZgHiY8VtT2QPJ/f2LWjymD5e5DnDDVQpxl8PoCg2TMgcgHMPPHqgAa9aVQ+X7SLoXg8IlA4JMQSLu1X/3R/tZbpbAqfLy+6B38D4c8wmq7kDJClo3vPgY8aNZhnA0E8tukpj6s5ZOflaNDZAtXS0nqhX51/mp/8na+H9dr9/LOWbPIGkLx92fa+MNeZSYelq3xAHz2YhefQdrjsdzDbhTvYQGlqj7eKu3LVeoAMd7QflxKJip7BjpS9YSU0VfRb/bfPXjNi+GdAn6VjjOeF+CrwH6rDf1BULaMtehw2UlYZU85S/9fRYm3M1I+UUEO8K1jSxDpXwkmLdlfKsu8jx9BSaUUcld3d8axun0drdj30h6zqG6nAujbu0FjFbdJ2BzfpXJ8GwMT/jojLIbXJ5GzsrSzt/gkOYwcQ96Xr0YlQLI/fMVCnUTKZ1407CZPxqS0xwbtGvyMeJJ3rcFgG/YdluPH0hNS6/gGEg4HYySXg1i5KmQF6SyCbPdKTG7H/RkHk=
  on:
    branch: master
    tags: true
    all_branches: true
